kind: pipeline
name: test

steps:
- name: test
  image: node:14
  commands:
  - cd ./server
  - npm ci
  - npm test

---
kind: pipeline
name: deploy

trigger:
  branch:
  - master
  event:
  - tag

steps:
- name: docker  
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: envoy89/myworstblog
    force_tag: true
    tags:
      - latest
      - ${DRONE_TAG}