version: "3"
services:
    api:
        build:
            context: ./
        ports:
            - "80:3000"
        depends_on:
            - db
        container_name: blog-api
        environment:
            - DB_USER=${DB_USER}
            - USER_PASSWORD=${USER_PASSWORD}
            - BaseHtmlUrl=${BaseHtmlUrl}
    db:
        image: mongo
        ports:
            - "27017:27017"
        container_name: blog-db