version: "3"
services:
    api:
        build: .
        ports:
            - "3000:3000"
        depends_on:
            - db
        container_name: blog-api
    db:
        image: mongo
        ports:
            - "27017:27017"
        container_name: blog-db