// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'selectableOption': string;
  'tagSearchContainer': string;
  'tagSearchText': string;
  'tagsSelector': string;
  'tagsSelectorList': string;
}
export const cssExports: CssExports;
export default cssExports;
