// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'tagsSelector': string;
  'tagsSelectorView': string;
}
export const cssExports: CssExports;
export default cssExports;
