// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'mainTopics': string;
  'paginationPanel': string;
  'topicWithPaginationContainer': string;
  'topicsAndTagsContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
