// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'topicArea': string;
  'topicField': string;
  'topicFieldWithText': string;
  'topicInfoArea': string;
  'topicName': string;
  'topicNameArea': string;
  'topicText': string;
  'topicTextArea': string;
}
export const cssExports: CssExports;
export default cssExports;
