// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttonsContainer': string;
  'createdDate': string;
  'nameClass': string;
  'tags': string;
  'topicControlButton': string;
  'topicRow': string;
  'topicText': string;
}
export const cssExports: CssExports;
export default cssExports;
