name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Read current version
        id: read_property
        uses: christian-draeger/read-properties@1.0.0
        with:
          path: './VERSION'
          property: 'version'
      - name: Current version
        run: echo ${{ steps.read_property.outputs.value }}
      
      - name: Bump release version
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.0.0
        with:
          current-version: ${{ steps.read_property.outputs.value }}
          version-fragment: 'bug'
      - name: New version
        run: echo ${{ steps.bump_version.outputs.next-version }}
